/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Dados.Imovel;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author pedrowarmlingbotelho
 */
public class ImoveisCadastro extends PadraoCadastro {

    ArrayList<Imovel> listaImovel;
    /**
     * Creates new form CadImoveis
     * @param listaImovel
     */
    public ImoveisCadastro(ArrayList<Imovel> listaImovel) {
        initComponents();
        this.listaImovel = listaImovel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelN = new javax.swing.JPanel();
        lTipo = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        tTamanho = new javax.swing.JTextField();
        lId = new javax.swing.JLabel();
        tId = new javax.swing.JTextField();
        lTamanho = new javax.swing.JLabel();
        lQuartos = new javax.swing.JLabel();
        tBanheiros = new javax.swing.JTextField();
        lBanheiros = new javax.swing.JLabel();
        tQuartos = new javax.swing.JTextField();
        tValor = new javax.swing.JTextField();
        lValor = new javax.swing.JLabel();
        lCEP = new javax.swing.JLabel();
        tfCEP = new javax.swing.JFormattedTextField();
        lEndereco = new javax.swing.JLabel();
        tEndereco = new javax.swing.JTextField();
        lCidade = new javax.swing.JLabel();
        tCidade = new javax.swing.JTextField();
        cbEstado = new javax.swing.JComboBox<>();
        lUF = new javax.swing.JLabel();

        setName("Cadastro de Imóveis"); // NOI18N

        lTipo.setText("Tipo do Imóvel:");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Apartamento", "Terreno", "Comercial" }));

        lId.setText("Identificação:");

        lTamanho.setText("Tamanho:");

        lQuartos.setText("Qtd. Quartos:");

        lBanheiros.setText("Qtd. Banheiros:");

        lValor.setText("Valor:");

        lCEP.setText("CEP:");

        try {
            tfCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lEndereco.setText("Endereço:");

        lCidade.setText("Cidade:");

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SE", "SP", "TO" }));
        cbEstado.setSelectedIndex(17);

        lUF.setText("UF:");

        javax.swing.GroupLayout painelNLayout = new javax.swing.GroupLayout(painelN);
        painelN.setLayout(painelNLayout);
        painelNLayout.setHorizontalGroup(
            painelNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNLayout.createSequentialGroup()
                .addGroup(painelNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelNLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(painelNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lTipo)
                            .addComponent(lId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelNLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(painelNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lCidade)
                            .addComponent(lTamanho)
                            .addComponent(lQuartos)
                            .addComponent(lValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelNLayout.createSequentialGroup()
                                .addGroup(painelNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(painelNLayout.createSequentialGroup()
                                        .addComponent(tQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lBanheiros)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tBanheiros, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(painelNLayout.createSequentialGroup()
                                        .addComponent(tCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(lUF)))
                                .addGap(18, 18, 18)
                                .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tValor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelNLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(painelNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lCEP)
                            .addComponent(lEndereco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        painelNLayout.setVerticalGroup(
            painelNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelNLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(painelNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTipo))
                .addGap(18, 18, 18)
                .addGroup(painelNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lId)
                    .addComponent(tId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(painelNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCEP))
                .addGap(8, 8, 8)
                .addGroup(painelNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEndereco)
                    .addComponent(tEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lUF)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCidade))
                .addGap(18, 18, 18)
                .addGroup(painelNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTamanho)
                    .addComponent(tTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lQuartos)
                    .addComponent(tQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lBanheiros)
                    .addComponent(tBanheiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lValor)
                    .addComponent(tValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        getContentPane().add(painelN, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel lBanheiros;
    private javax.swing.JLabel lCEP;
    private javax.swing.JLabel lCidade;
    private javax.swing.JLabel lEndereco;
    private javax.swing.JLabel lId;
    private javax.swing.JLabel lQuartos;
    private javax.swing.JLabel lTamanho;
    private javax.swing.JLabel lTipo;
    private javax.swing.JLabel lUF;
    private javax.swing.JLabel lValor;
    private javax.swing.JPanel painelN;
    private javax.swing.JTextField tBanheiros;
    private javax.swing.JTextField tCidade;
    private javax.swing.JTextField tEndereco;
    private javax.swing.JTextField tId;
    private javax.swing.JTextField tQuartos;
    private javax.swing.JTextField tTamanho;
    private javax.swing.JTextField tValor;
    private javax.swing.JFormattedTextField tfCEP;
    // End of variables declaration//GEN-END:variables


    @Override
    public void bConfirmarActionPerformed(ActionEvent ae) {
        
        if((tId.getText().equals("")) || 
           (tTamanho.getText().equals("")) || 
           (tQuartos.getText().equals("")) || 
           (tBanheiros.getText().equals("")) || 
           (tValor.getText().equals("")) ||
           (tfCEP.getText().equals("")) ||
           (tEndereco.getText().equals("")) ||
           (tCidade.getText().equals("")))
        {
            JOptionPane.showMessageDialog(null, "Por favor informe todos os campos!");
            return;
        }
        
        for (Imovel imoveis : listaImovel) {
            if (imoveis.getId() == Integer.parseInt(tId.getText())) {
                JOptionPane.showMessageDialog(this, "Já existe um imóvel com esse ID", "Mensagem de erro", JOptionPane.ERROR_MESSAGE);
                tId.setText("");
                return;
            }
        }
        
        Imovel imoveis = new Imovel();
        imoveis.setTipo((String)cbTipo.getSelectedItem());
        imoveis.setId(Integer.parseInt(tId.getText()));
        imoveis.setCep(tfCEP.getText());
        imoveis.setEndereco(tEndereco.getText());
        imoveis.setCidade(tCidade.getText());
        imoveis.setUf((String)cbEstado.getSelectedItem());
        imoveis.setTamanho(tTamanho.getText());
        imoveis.setQuartos(tQuartos.getText());
        imoveis.setBanheiros(tBanheiros.getText());
        imoveis.setValor(tValor.getText());
        limparTela();
        listaImovel.add(imoveis);
        JOptionPane.showMessageDialog(null, "Itens inseridos com sucesso!");
    }

    @Override
    public void bLimparActionPerformed(ActionEvent ae) {
        limparTela();
    }

    @Override
    public void bCancelarActionPerformed(ActionEvent ae) {
        this.dispose();
    }
    
    public void limparTela(){
        tId.setText("");
        tTamanho.setText("");
        tfCEP.setText("");
        tEndereco.setText("");
        tCidade.setText("");
        tTamanho.setText("");
        tQuartos.setText("");
        tBanheiros.setText("");
        tValor.setText("");
    }
}
