/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Dados.Cliente;
import Dados.Imovel;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pedrowarmlingbotelho
 */
public class ImoveisMostrar extends PadraoMostrar {

    DefaultTableModel tabela;
    ArrayList<Imovel> listaImovel;
    /**
     * Creates new form ImoveisMostrar
     * @param listaImovel
     */
    public ImoveisMostrar(ArrayList<Imovel> listaImovel) {
        initComponents();
        tabela = (DefaultTableModel) tabelaImovel.getModel();
        this.listaImovel = listaImovel;
        insereTabela();
    }
    
    public void insereTabela(){
        for (Imovel imoveis : listaImovel) {
            Object[] dados = {imoveis.getTipo(), imoveis.getId(), imoveis.getEndereco(), imoveis.getCidade(), 
                                imoveis.getUf(), imoveis.getTamanho(), imoveis.getQuartos(), imoveis.getBanheiros(), imoveis.getValor()};
            tabela.addRow(dados);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabelaImoveis = new javax.swing.JScrollPane();
        tabelaImovel = new javax.swing.JTable();

        tabelaImovel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "ID", "Endereço", "Cidade", "UF", "Tamanho", "Quartos", "Banheiros", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaImoveis.setViewportView(tabelaImovel);
        if (tabelaImovel.getColumnModel().getColumnCount() > 0) {
            tabelaImovel.getColumnModel().getColumn(0).setPreferredWidth(50);
            tabelaImovel.getColumnModel().getColumn(1).setPreferredWidth(10);
            tabelaImovel.getColumnModel().getColumn(2).setPreferredWidth(100);
            tabelaImovel.getColumnModel().getColumn(3).setPreferredWidth(50);
            tabelaImovel.getColumnModel().getColumn(4).setPreferredWidth(8);
            tabelaImovel.getColumnModel().getColumn(5).setPreferredWidth(10);
            tabelaImovel.getColumnModel().getColumn(6).setPreferredWidth(8);
            tabelaImovel.getColumnModel().getColumn(7).setPreferredWidth(8);
            tabelaImovel.getColumnModel().getColumn(8).setPreferredWidth(15);
        }

        getContentPane().add(tabelaImoveis, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void bSairActionPerformed(ActionEvent ae) {
        this.dispose();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane tabelaImoveis;
    private javax.swing.JTable tabelaImovel;
    // End of variables declaration//GEN-END:variables
}
