/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author pedrowarmlingbotelho
 */
public abstract class PadraoExcluir extends javax.swing.JInternalFrame implements ActionListener{

    /**
     * Creates new form PadraoExcluir
     */
    public PadraoExcluir() {
        initComponents();
        bConsultar.addActionListener(this);
        bCancelar.addActionListener(this);
        bExcluir.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelN = new javax.swing.JPanel();
        lId = new javax.swing.JLabel();
        tId = new javax.swing.JTextField();
        bConsultar = new javax.swing.JButton();
        painelS = new javax.swing.JPanel();
        bExcluir = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        lId.setText("Identificação:");

        bConsultar.setText("Consultar");

        javax.swing.GroupLayout painelNLayout = new javax.swing.GroupLayout(painelN);
        painelN.setLayout(painelNLayout);
        painelNLayout.setHorizontalGroup(
            painelNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tId, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bConsultar)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        painelNLayout.setVerticalGroup(
            painelNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(painelNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lId)
                    .addComponent(tId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bConsultar))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(painelN, java.awt.BorderLayout.NORTH);

        bExcluir.setText("Excluir");

        bCancelar.setText("Cancelar");

        javax.swing.GroupLayout painelSLayout = new javax.swing.GroupLayout(painelS);
        painelS.setLayout(painelSLayout);
        painelSLayout.setHorizontalGroup(
            painelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(bExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(bCancelar)
                .addGap(57, 57, 57))
        );

        painelSLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bCancelar, bExcluir});

        painelSLayout.setVerticalGroup(
            painelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(painelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bExcluir)
                    .addComponent(bCancelar))
                .addGap(30, 30, 30))
        );

        painelSLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bCancelar, bExcluir});

        getContentPane().add(painelS, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bConsultar;
    private javax.swing.JButton bExcluir;
    private javax.swing.JLabel lId;
    private javax.swing.JPanel painelN;
    private javax.swing.JPanel painelS;
    private javax.swing.JTextField tId;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        switch(e.getActionCommand()){
            case "Consultar":
                bConsultarActionPerformed(e);
                break;
            case "Excluir":
                bExcluirActionPerformed(e);
                break;
            case "Cancelar":
                bCancelarActionPerformed(e);
                break;
        }
    }
    public abstract void bConsultarActionPerformed(ActionEvent ae);
    public abstract void bExcluirActionPerformed(ActionEvent ae);
    public abstract void bCancelarActionPerformed(ActionEvent ae);

}
