/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author pedrowarmlingbotelho
 */
public abstract class PadraoEditar extends javax.swing.JInternalFrame implements ActionListener {

    /**
     * Creates new form PadraoEditar
     */
    public PadraoEditar() {
        initComponents();
        bSalvar.addActionListener(this);
        bLimpar.addActionListener(this);
        bCancelar.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelS = new javax.swing.JPanel();
        bCancelar = new javax.swing.JButton();
        bSalvar = new javax.swing.JButton();
        bLimpar = new javax.swing.JButton();

        bCancelar.setText("Cancelar");

        bSalvar.setText("Salvar");

        bLimpar.setText("Limpar");

        javax.swing.GroupLayout painelSLayout = new javax.swing.GroupLayout(painelS);
        painelS.setLayout(painelSLayout);
        painelSLayout.setHorizontalGroup(
            painelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(bSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(bLimpar)
                .addGap(18, 18, 18)
                .addComponent(bCancelar)
                .addGap(31, 31, 31))
        );

        painelSLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bCancelar, bLimpar, bSalvar});

        painelSLayout.setVerticalGroup(
            painelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(painelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar)
                    .addComponent(bSalvar)
                    .addComponent(bLimpar))
                .addGap(22, 22, 22))
        );

        getContentPane().add(painelS, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bLimpar;
    public javax.swing.JButton bSalvar;
    private javax.swing.JPanel painelS;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        switch(e.getActionCommand()){
            case "Salvar":
                bSalvarActionPerformed(e);
                break;
            case "Limpar":
                bLimparActionPerformed(e);
                break;
            case "Cancelar":
                bCancelarActionPerformed(e);
                break;
        }
    }
    public abstract void bSalvarActionPerformed(ActionEvent ae);
    public abstract void bLimparActionPerformed(ActionEvent ae);
    public abstract void bCancelarActionPerformed(ActionEvent ae);

}
