/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Dados.Cliente;
import Dados.Imovel;
import Dados.Locacao;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pedrowarmlingbotelho
 */
public class Relatorio extends PadraoMostrar {

    DefaultTableModel tabela;
    ArrayList<Locacao> listaLocacao;
    /**
     * Creates new form LocacaoMostrar
     * @param listaLocacao
     */
    public Relatorio(ArrayList<Locacao> listaLocacao) {
        initComponents();
        tabela = (DefaultTableModel) tabelaLocacao.getModel();
        this.listaLocacao = listaLocacao;
        insereTabela();
    }
    
    public void insereTabela(){
        for (Locacao locacao : listaLocacao) {
            Object[] dados = {locacao.getId(), locacao.getIdCliente(), locacao.getIdImovel(), locacao.getValor(), locacao.getDataInicio(), locacao.getDataFim()};
            tabela.addRow(dados);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLocacao = new javax.swing.JTable();

        tabelaLocacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Locação", "Cliente", "Imóvel", "Valor", "Data Inicio", "Data Fim"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaLocacao);
        if (tabelaLocacao.getColumnModel().getColumnCount() > 0) {
            tabelaLocacao.getColumnModel().getColumn(0).setPreferredWidth(15);
            tabelaLocacao.getColumnModel().getColumn(1).setPreferredWidth(15);
            tabelaLocacao.getColumnModel().getColumn(2).setPreferredWidth(15);
            tabelaLocacao.getColumnModel().getColumn(3).setPreferredWidth(15);
            tabelaLocacao.getColumnModel().getColumn(4).setPreferredWidth(15);
            tabelaLocacao.getColumnModel().getColumn(5).setPreferredWidth(15);
        }

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaLocacao;
    // End of variables declaration//GEN-END:variables

    @Override
    public void bSairActionPerformed(ActionEvent ae) {
        this.dispose();
    }
}
