/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Dados.Cliente;
import Dados.Imovel;
import Dados.Locacao;
import java.util.ArrayList;

/**
 *
 * @author pedrowarmlingbotelho
 */
public class TelaIncio extends javax.swing.JFrame {

    ArrayList<Cliente> listaCliente = new ArrayList<>();
    ArrayList<Imovel> listaImovel = new ArrayList<>();
    ArrayList<Locacao> listaLocacao = new ArrayList<>();
    /**
     * Creates new form TelaIncio
     */
    public TelaIncio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        barraMenu = new javax.swing.JMenuBar();
        mImoveis = new javax.swing.JMenu();
        miCadastrar = new javax.swing.JMenuItem();
        miEditar = new javax.swing.JMenuItem();
        miMostrar = new javax.swing.JMenuItem();
        miExcluir = new javax.swing.JMenuItem();
        mClientes = new javax.swing.JMenu();
        mcCadastrar = new javax.swing.JMenuItem();
        mcEditar = new javax.swing.JMenuItem();
        mcMostrar = new javax.swing.JMenuItem();
        mcExcluir = new javax.swing.JMenuItem();
        mLocacao = new javax.swing.JMenu();
        mlAdicionar = new javax.swing.JMenuItem();
        mlRenovar = new javax.swing.JMenuItem();
        mlExcluir = new javax.swing.JMenuItem();
        mlMostrar = new javax.swing.JMenuItem();
        mRelatorio = new javax.swing.JMenu();
        mrGerar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Cadastro");
        setExtendedState(MAXIMIZED_BOTH);
        getContentPane().add(Desktop, java.awt.BorderLayout.CENTER);

        mImoveis.setText("Imóveis");

        miCadastrar.setText("Cadastrar");
        miCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastrarActionPerformed(evt);
            }
        });
        mImoveis.add(miCadastrar);

        miEditar.setText("Editar");
        miEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEditarActionPerformed(evt);
            }
        });
        mImoveis.add(miEditar);

        miMostrar.setText("Mostrar");
        miMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMostrarActionPerformed(evt);
            }
        });
        mImoveis.add(miMostrar);

        miExcluir.setText("Excluir");
        miExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExcluirActionPerformed(evt);
            }
        });
        mImoveis.add(miExcluir);

        barraMenu.add(mImoveis);

        mClientes.setText("Clientes");

        mcCadastrar.setText("Cadastrar");
        mcCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcCadastrarActionPerformed(evt);
            }
        });
        mClientes.add(mcCadastrar);

        mcEditar.setText("Editar");
        mcEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcEditarActionPerformed(evt);
            }
        });
        mClientes.add(mcEditar);

        mcMostrar.setText("Mostrar");
        mcMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcMostrarActionPerformed(evt);
            }
        });
        mClientes.add(mcMostrar);

        mcExcluir.setText("Excluir");
        mcExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcExcluirActionPerformed(evt);
            }
        });
        mClientes.add(mcExcluir);

        barraMenu.add(mClientes);

        mLocacao.setText("Locação");

        mlAdicionar.setText("Adicionar");
        mlAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlAdicionarActionPerformed(evt);
            }
        });
        mLocacao.add(mlAdicionar);

        mlRenovar.setText("Renovar");
        mlRenovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlRenovarActionPerformed(evt);
            }
        });
        mLocacao.add(mlRenovar);

        mlExcluir.setText("Excluir");
        mlExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlExcluirActionPerformed(evt);
            }
        });
        mLocacao.add(mlExcluir);

        mlMostrar.setText("Mostrar");
        mlMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlMostrarActionPerformed(evt);
            }
        });
        mLocacao.add(mlMostrar);

        barraMenu.add(mLocacao);

        mRelatorio.setText("Relatório");

        mrGerar.setText("Gerar");
        mRelatorio.add(mrGerar);

        barraMenu.add(mRelatorio);

        setJMenuBar(barraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mcCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcCadastrarActionPerformed
        ClienteCadastro telaCadCliente = new ClienteCadastro(listaCliente);
        telaCadCliente.setVisible(true);
        this.Desktop.add(telaCadCliente);
    }//GEN-LAST:event_mcCadastrarActionPerformed

    private void miCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastrarActionPerformed
        ImoveisCadastro telaCadImoveis = new ImoveisCadastro(listaImovel);
        telaCadImoveis.setVisible(true);
        this.Desktop.add(telaCadImoveis);
    }//GEN-LAST:event_miCadastrarActionPerformed

    private void mlAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlAdicionarActionPerformed
        LocacaoCadastro telaCadLocacao = new LocacaoCadastro(listaLocacao, listaCliente, listaImovel, Desktop);
        telaCadLocacao.setVisible(true);
        this.Desktop.add(telaCadLocacao);
    }//GEN-LAST:event_mlAdicionarActionPerformed

    private void mcExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcExcluirActionPerformed
        ClienteExcluir telaExcluirCliente = new ClienteExcluir(listaCliente, Desktop);
        telaExcluirCliente.setVisible(true);
        this.Desktop.add(telaExcluirCliente);
    }//GEN-LAST:event_mcExcluirActionPerformed

    private void mcEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcEditarActionPerformed
        ClienteEditar telaEditarCliente = new ClienteEditar(listaCliente, Desktop);
        telaEditarCliente.setVisible(true);
        this.Desktop.add(telaEditarCliente);
    }//GEN-LAST:event_mcEditarActionPerformed

    private void mcMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcMostrarActionPerformed
        ClienteMostrar telaMostrarCliente = new ClienteMostrar(listaCliente);
        telaMostrarCliente.setVisible(true);
        this.Desktop.add(telaMostrarCliente);
    }//GEN-LAST:event_mcMostrarActionPerformed

    private void miEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEditarActionPerformed
        ImoveisEditar telaEditarImoveis = new ImoveisEditar();
        telaEditarImoveis.setVisible(true);
        this.Desktop.add(telaEditarImoveis);
    }//GEN-LAST:event_miEditarActionPerformed

    private void miMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMostrarActionPerformed
        ImoveisMostrar telaMostrarImoveis = new ImoveisMostrar(listaImovel);
        telaMostrarImoveis.setVisible(true);
        this.Desktop.add(telaMostrarImoveis);
    }//GEN-LAST:event_miMostrarActionPerformed

    private void miExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExcluirActionPerformed
        ImoveisExcluir telaExcluirImoveis = new ImoveisExcluir(listaImovel, Desktop);
        telaExcluirImoveis.setVisible(true);
        this.Desktop.add(telaExcluirImoveis);
    }//GEN-LAST:event_miExcluirActionPerformed

    private void mlExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlExcluirActionPerformed
        LocacaoExcluir telaExcluirLocacao = new LocacaoExcluir(listaLocacao, Desktop);
        telaExcluirLocacao.setVisible(true);
        this.Desktop.add(telaExcluirLocacao);
    }//GEN-LAST:event_mlExcluirActionPerformed

    private void mlRenovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlRenovarActionPerformed
        LocacaoRenovar telaRenovarLocacao = new LocacaoRenovar();
        telaRenovarLocacao.setVisible(true);
        this.Desktop.add(telaRenovarLocacao);
    }//GEN-LAST:event_mlRenovarActionPerformed

    private void mlMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlMostrarActionPerformed
        LocacaoMostrar telaMostrarLocacao = new LocacaoMostrar(listaLocacao);
        telaMostrarLocacao.setVisible(true);
        this.Desktop.add(telaMostrarLocacao);
    }//GEN-LAST:event_mlMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaIncio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaIncio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaIncio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaIncio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaIncio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu mClientes;
    private javax.swing.JMenu mImoveis;
    private javax.swing.JMenu mLocacao;
    private javax.swing.JMenu mRelatorio;
    private javax.swing.JMenuItem mcCadastrar;
    private javax.swing.JMenuItem mcEditar;
    private javax.swing.JMenuItem mcExcluir;
    private javax.swing.JMenuItem mcMostrar;
    private javax.swing.JMenuItem miCadastrar;
    private javax.swing.JMenuItem miEditar;
    private javax.swing.JMenuItem miExcluir;
    private javax.swing.JMenuItem miMostrar;
    private javax.swing.JMenuItem mlAdicionar;
    private javax.swing.JMenuItem mlExcluir;
    private javax.swing.JMenuItem mlMostrar;
    private javax.swing.JMenuItem mlRenovar;
    private javax.swing.JMenuItem mrGerar;
    // End of variables declaration//GEN-END:variables
}
