/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controle;

/**
 *
 * @author pedrowarmlingbotelho
 */
public class TelaIncio extends javax.swing.JFrame {

    /**
     * Creates new form TelaIncio
     */
    public TelaIncio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        mImoveis = new javax.swing.JMenu();
        miCadastrar = new javax.swing.JMenuItem();
        miEditar = new javax.swing.JMenuItem();
        miExcluir = new javax.swing.JMenuItem();
        mClientes = new javax.swing.JMenu();
        mcCadastrar = new javax.swing.JMenuItem();
        mcEditar = new javax.swing.JMenuItem();
        mcExcluir = new javax.swing.JMenuItem();
        mLocacao = new javax.swing.JMenu();
        mlAdicionar = new javax.swing.JMenuItem();
        mlExcluir = new javax.swing.JMenuItem();
        mlRenovar = new javax.swing.JMenuItem();
        mRelatorio = new javax.swing.JMenu();
        mrGerar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Cadastro");
        setExtendedState(MAXIMIZED_BOTH);
        getContentPane().add(Desktop, java.awt.BorderLayout.CENTER);

        mImoveis.setText("Imóveis");

        miCadastrar.setText("Cadastrar");
        miCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastrarActionPerformed(evt);
            }
        });
        mImoveis.add(miCadastrar);

        miEditar.setText("Editar");
        mImoveis.add(miEditar);

        miExcluir.setText("Excluir");
        mImoveis.add(miExcluir);

        jMenuBar2.add(mImoveis);

        mClientes.setText("Clientes");

        mcCadastrar.setText("Cadastrar");
        mcCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcCadastrarActionPerformed(evt);
            }
        });
        mClientes.add(mcCadastrar);

        mcEditar.setText("Editar");
        mClientes.add(mcEditar);

        mcExcluir.setText("Excluir");
        mClientes.add(mcExcluir);

        jMenuBar2.add(mClientes);

        mLocacao.setText("Locação");

        mlAdicionar.setText("Adicionar");
        mlAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlAdicionarActionPerformed(evt);
            }
        });
        mLocacao.add(mlAdicionar);

        mlExcluir.setText("Excluir");
        mLocacao.add(mlExcluir);

        mlRenovar.setText("Renovar");
        mLocacao.add(mlRenovar);

        jMenuBar2.add(mLocacao);

        mRelatorio.setText("Relatório");

        mrGerar.setText("Gerar");
        mRelatorio.add(mrGerar);

        jMenuBar2.add(mRelatorio);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mcCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcCadastrarActionPerformed
        CadCliente telaCadCliente = new CadCliente();
        telaCadCliente.setVisible(true);
        this.Desktop.add(telaCadCliente);
    }//GEN-LAST:event_mcCadastrarActionPerformed

    private void miCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastrarActionPerformed
        CadImoveis telaCadImoveis = new CadImoveis();
        telaCadImoveis.setVisible(true);
        this.Desktop.add(telaCadImoveis);
    }//GEN-LAST:event_miCadastrarActionPerformed

    private void mlAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlAdicionarActionPerformed
        CadLocacao telaCadLocacao = new CadLocacao();
        telaCadLocacao.setVisible(true);
        this.Desktop.add(telaCadLocacao);
    }//GEN-LAST:event_mlAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaIncio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaIncio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaIncio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaIncio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaIncio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu mClientes;
    private javax.swing.JMenu mImoveis;
    private javax.swing.JMenu mLocacao;
    private javax.swing.JMenu mRelatorio;
    private javax.swing.JMenuItem mcCadastrar;
    private javax.swing.JMenuItem mcEditar;
    private javax.swing.JMenuItem mcExcluir;
    private javax.swing.JMenuItem miCadastrar;
    private javax.swing.JMenuItem miEditar;
    private javax.swing.JMenuItem miExcluir;
    private javax.swing.JMenuItem mlAdicionar;
    private javax.swing.JMenuItem mlExcluir;
    private javax.swing.JMenuItem mlRenovar;
    private javax.swing.JMenuItem mrGerar;
    // End of variables declaration//GEN-END:variables
}
